apiVersion: v1
kind: Pod
metadata:
  name: rpsls-pod
  labels:
    app: rpsls
spec:
  containers:
    - name: rpsls-backend
      image: localhost/rpsls-backend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
          hostPort: 8000
      resources: {}
      
    - name: rpsls-frontend
      image: localhost/rpsls-frontend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
          hostPort: 3000
      resources: {}
