from typing import Optional, Literal
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from engine import generate_computer_choice, evaluate_round

app = FastAPI(
    title="Rock-Paper-Scissors-Lizard-Spock API",
    description="Secure, stateless backend for choice generation and win/loss evaluation.",
    version="0.1.0",
)

# Enable CORS for the frontend origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class PlayRequest(BaseModel):
    player_choice: Optional[Literal["rock", "paper", "scissors", "lizard", "spock"]] = (
        Field(
            default=None,
            description="The player's chosen hand. Null indicates a forfeit due to timeout.",
        )
    )


class PlayResponse(BaseModel):
    player_choice: Optional[str] = Field(
        ..., description="The option selected by the player, or null if forfeit."
    )
    computer_choice: str = Field(
        ..., description="The option randomly generated by the computer."
    )
    result: Literal["player_win", "computer_win", "tie"] = Field(
        ..., description="Outcome of the round."
    )
    message: str = Field(
        ...,
        description="Explanatory text describing the result based on the game rules.",
    )


@app.post("/api/play", response_model=PlayResponse)
def play_round(request: PlayRequest):
    """
    Core stateless game play endpoint.
    Generates computer choice, evaluates result, and returns the round resolution details.
    """
    try:
        # Generate the computer's choice randomly on the secure backend
        computer_choice = generate_computer_choice()

        # Evaluate the round outcome
        result, message = evaluate_round(request.player_choice, computer_choice)

        return PlayResponse(
            player_choice=request.player_choice,
            computer_choice=computer_choice,
            result=result,
            message=message,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {str(e)}")


@app.get("/health")
def health_check():
    """Simple health check endpoint."""
    return {"status": "ok"}
